// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  la_la: defineAsyncComponent(() => import("./LaLa/index.vue")),
  links: defineAsyncComponent(() => import("./Links/index.vue")),
  rich_text: defineAsyncComponent(() => import("./RichText/index.vue")),
  small_text: defineAsyncComponent(() => import("./SmallText/index.vue")),
});
